#!/usr/bin/env bash

# @Author: S. Sharma <silentcat>
# @Date:   2019-02-02T11:52:07-06:00
# @Email:  silentcat@protonmail.com
# @Last modified by:   silentcat
# @Last modified time: 2019-02-04T20:53:22-06:00


if [[ "$1" == "" ]]
then

  cat <<EOF
  ./make_tests [c|d]:

  c - Creates symbolic links to all *_test files in the test/ directory.
  d - Deletes symbolic links to all *_test files in the test/ directory.
EOF
  printf "\n"
  exit
fi

if [[ "$1" == "c" ]]
then
  for i in $(ls test | grep -e "_test$")
  do
    ln -s "test/$i" $i
  done
elif [[ "$1" == "d" ]]
then
  for i in $(ls test | grep -e "_test$")
  do
    rm $i
  done
  rm liberrors_test
else
  echo "Command unrecognized."
fi
